name: ci

env:
  DEPLOY_ENABLED: false

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  build:
    runs-on: ubuntu-latest

    if: env.DEPLOY_ENABLED == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hello
        run: echo "Hello from CI!"
