name: ML.NET CI

env:
  DEPLOY_ENABLED: false

on:
  push:
    paths:
      - 'ML.NET/**'
  pull_request:
    paths:
      - 'ML.NET/**'

if: env.DEPLOY_ENABLED == 'true'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Find and build all .csproj
        run: |
          find ML.NET -name "*.csproj"
          for proj in $(find ML.NET -name "*.csproj"); do
            echo "Building $proj"
            dotnet restore "$proj"
            dotnet build "$proj" --no-restore --configuration Release
            dotnet test "$proj" --no-build --verbosity normal || true
          done
